name: "Deploy production"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
      - run: env
        env:
          TINA_BRANCH: ${{ vars.TINA_BRANCH }}
          TINA_CLIENT_ID: ${{ vars.TINA_CLIENT_ID }}
          TINA_TOKEN: ${{ vars.TINA_TOKEN }}

          TINA_ENV_BRANCH: ${{ vars.ENV_TINA_BRANCH }}
          TINA_SEC_BRANCH: ${{ secrets.TINA_BRANCH }}
          TINA_VAR_BRANCH: ${{ vars.TINA_BRANCH }}
      - run: npm ci
      - run: npm run build
        env:
          TINA_BRANCH: ${{ vars.TINA_BRANCH }}
          TINA_CLIENT_ID: ${{ vars.TINA_CLIENT_ID }}
          TINA_TOKEN: ${{ vars.TINA_TOKEN }}
      - run: npm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
